stages:
  - build
  - publish

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
  script:
    - cd src
    - dotnet restore
    - dotnet test -c Release
    # Dirty hack: when this step is run not on tag, use "0.0.0" as a version placeholder
    # "publish" step is run only on tags and expect valid tag names which can be used as a version, e.g. "0.0.4" or "1.0.0-rc1"
    - dotnet build -c Release /p:PackageVersion=${CI_COMMIT_TAG:-0.0.0}
  artifacts:
    expire_in: 2 days
    paths:
      - src/Tp.Core.Functional/bin/Release

publish:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
  dependencies:
    - build
  only:
    - tags
  when: manual
  script:
    - dotnet nuget push ./src/Tp.Core.Functional/bin/Release/Tp.Core.Functional.${CI_COMMIT_TAG}.nupkg -k ${NUGET_API_KEY} -s https://www.nuget.org/api/v2/package
